## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
## Resources:
##     https://access.redhat.com/articles/3626371#bgenerating-a-new-offline-tokenb-3
##     https://access.redhat.com/management/api
##     https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_a_standard_rhel_8_installation/downloading-beta-installation-images_installing-rhel
##     https://github.com/redhat-cop/rhel-edge-automation-arch/blob/main/ansible/roles/redhat-image-downloader/tasks/main.yaml
##


- name: "iso-download : BEGIN Red Hat Downloads"
  delegate_to: localhost
  throttle: 1

  block:

      - set_fact:
          redhat_api_url: "https://api.access.redhat.com/management/v1"
          redhat_sso_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
  
      - name: "iso-download : attempt locate/download RED HAT ISO(s)"
        include_tasks:
          file: iso-download-redhat-includetasks.yml
        with_items:
          - { filename: "{{ xtoph_deploy.kickstart_profile.boot_iso | default('') }}",
              checksum: "{{ xtoph_deploy.kickstart_profile.boot_iso_chksum | default('') }}",
              version:  "{{ xtoph_deploy.kickstart_profile.version | default('') }}",
              arch:     "{{ xtoph_deploy.kickstart_profile.arch | default('') }}",
              vender:   "{{ xtoph_deploy.kickstart_profile.vender  }}" }
          - { filename: "{{ xtoph_deploy.kickstart_profile.repo_iso | default('') }}",
              checksum: "{{ xtoph_deploy.kickstart_profile.repo_iso_chksum | default('') }}",
              version:  "{{ xtoph_deploy.kickstart_profile.version | default('') }}",
              arch:     "{{ xtoph_deploy.kickstart_profile.arch | default('') }}",
              vender:   "{{ xtoph_deploy.kickstart_profile.vender }}" }
        loop_control:
          loop_var: iso_detail

  when: 
      - xtoph_deploy.kickstart_profile is defined 
      - xtoph_deploy.kickstart_profile.vender is defined 
      - xtoph_deploy.kickstart_profile.vender == "redhat"

  ## End-Of-Block


- name: "iso-download : BEGIN Generic Downloads"
  delegate_to: localhost
  throttle: 1


  block:

        - set_fact:
            redhat_api_url: "https://api.access.redhat.com/management/v1"
            redhat_sso_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
  
        - name: "iso-download : attempt locate/download publically accessible ISO(s)"
          include_tasks:
            file: iso-download-includetasks.yml
          with_items:
            - { filename: "{{ xtoph_deploy.kickstart_profile.boot_iso | default('') }}",
                checksum: "{{ xtoph_deploy.kickstart_profile.boot_iso_chksum | default('') }}",
                version:  "{{ xtoph_deploy.kickstart_profile.version | default('') }}",
                arch:     "{{ xtoph_deploy.kickstart_profile.arch | default('') }}",
                url_iso:  "{{ xtoph_deploy.kickstart_profile.url_iso | default('') }}",
                vender:   "{{ xtoph_deploy.kickstart_profile.vender  }}" }
            - { filename: "{{ xtoph_deploy.kickstart_profile.repo_iso | default('') }}",
                checksum: "{{ xtoph_deploy.kickstart_profile.repo_iso_chksum | default('') }}",
                version:  "{{ xtoph_deploy.kickstart_profile.version | default('') }}",
                arch:     "{{ xtoph_deploy.kickstart_profile.arch | default('') }}",
                url_iso:  "{{ xtoph_deploy.kickstart_profile.url_iso | default('') }}",
                vender:   "{{ xtoph_deploy.kickstart_profile.vender }}" }
          loop_control:
            loop_var: iso_detail

  when:
      - xtoph_deploy.kickstart_profile is defined
      - xtoph_deploy.kickstart_profile.vender is defined
      - xtoph_deploy.kickstart_profile.vender != "redhat"
      - xtoph_deploy.kickstart_profile.url_iso != ""

  ## End-Of-Block

